name: Terraform Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Enables manual apply

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Auto-format Terraform files
        run: terraform fmt -recursive

      - name: Terraform Plan
        run: terraform plan

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan  # Optional: ensures plan job completes first
    if: github.event_name == 'workflow_dispatch'  # Only runs on manual trigger

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
